### ISSUE TITLE
Question about model.json

### ISSUE THREAD

**Issue by opchronatron** [Nor-s/Anim#20]
Can you point me to where model.json is generated? What format is expected? Thank you!

**Comment by Nor-s** [comment]
@opchronatron 

[model.json(xbot.fbx)](https://github.com/user-attachments/files/16738822/model.json)


model.json is created when you run Python in Anim.exe menu.
It is created in the path where Anim.exe is located.



This is a json file containing the binding pose of the model currently selected in Anim.exe.
Here the model must have the same bone name as the Mixamo model.

The reason I passed model.json was because the model's binding pose was different for each character.
Refer to this model.json in the python code and use it to retarget the vertex of mediapipe.

```json
{
	"name" : "model",
	"node" : 
	{
		"child" : 
		[
			{
				"child" : 
				[
					{
						"child" : 
						[
							{
								"child" : 
								[
									{
										"child" : 
										[
											{
												"child" : 
												[
													{
														"child" : [],
														"name" : "mixamorig:HeadTop_End",
														"parent_name" : "mixamorig:Head",
														"position" : 
														{
															"x" : -5.9122899718350164e-19,
															"y" : 21.749261856079102,
															"z" : -2.248201624865942e-15
														},
														"rotation" : 
														{
															"w" : 1.0,
															"x" : 0.0,
															"y" : 0.0,
															"z" : 0.0
														},
														"scale" : 
														{
															"x" : 1.0,
															"y" : 1.0,
															"z" : 1.0
														}
														
```
